# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- lint
- test
- build

.rust-check:
  stage: lint
  image: rust
  before_script:
    - apt update
    - apt install protobuf-compiler -y

.rust-build:
  stage: build
  image: rust
  before_script:
    - apt update
    - apt install protobuf-compiler -y
  artifacts:
    untracked: false
    when: on_success
    access: 'developer'
    expire_in: "30 days"

rust-check:client:
  extends: .rust-check
  script:
    - cd client/
    - cargo check

rust-check:server:
  extends: .rust-check
  script:
    - cd server/
    - cargo check

rust-build:client:
  extends: .rust-build
  script:
    - cd client/
    - cargo build --release
  artifacts:
    paths:
      - client/target/release/

rust-build:server:
  extends: .rust-build
  script:
    - cd server/
    - cargo build --release
  artifacts:
    paths:
      - server/target/release/

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
