---

- name: "Install scripts for the RMON-{{ variant }}"
  hosts: all
  gather_facts: true

  vars:
    variant: ~

  tasks:

    - name: Check if the rust toolchain is installed
      command: which cargo
      changed_when: false
      tags: install-src

    - name: Install build requirements
      apt:
        pkg:
          - build-essential
          - protobuf-compiler
        update_cache: true
      become: true
      tags: install-src

    - name: "Build {{ variant }} binary from source"
      command:
        cmd: cargo build --release
        chdir: "/tmp/rmon-installer/rmon/{{ variant }}"
        creates: /tmp/rmon-installer/rmon/{{ variant }}/target/release/rmon-{{ variant }}
      tags: install-src

    - name: "Copy {{ variant }} src build to installer directory"
      copy:
        src: /tmp/rmon-installer/rmon/{{ variant }}/target/release/rmon-{{ variant }}
        dest: /tmp/rmon-installer/rmon-{{ variant }}
        mode: '0755'
        remote_src: true
      tags: install-src

    - name: Create rmon system user
      user:
        name: rmon
        comment: System user for the RMON suite
        system: true
      become: true
      tags:
        - install
        - install-src

    - name: Create target configuration directory /etc/rmon
      file:
        path: /etc/rmon
        owner: root
        group: rmon
        mode: '0750'
        state: directory
      become: true
      tags:
        - install
        - install-src

    - name: "Create target installation directory {{ install_dir }}/bin"
      file:
        path: "{{ install_dir }}/bin"
        owner: rmon
        group: rmon
        mode: '0755'
        state: directory
      become: true
      tags:
        - install
        - install-src

    - name: "Copy {{ variant }} binary to target installation directory"
      copy:
        src: "/tmp/rmon-installer/rmon-{{ variant }}"
        dest: "{{ install_dir }}/bin/rmon-{{ variant }}"
        remote_src: true
        owner: rmon
        group: rmon
        mode: '0755'
      become: true
      tags:
        - install
        - install-src

    - name: "Copy the {{ variant }} default config to target config directory"
      copy:
        src: "rmon-{{ variant }}.yaml"
        dest: "/etc/rmon/rmon-{{ variant }}.yaml"
        owner: root
        group: root
        mode: '0644'
      become: true
      tags:
        - install
        - install-src

    - name: "Copy {{ variant }} systemd unit file"
      template:
        src: rmon.service
        dest: "/usr/lib/systemd/system/rmon-{{ variant }}.service"
        owner: root
        group: root
        mode: '0644'
      become: true
      notify: "Start and enable rmon-{{ variant }}"
      tags:
        - install
        - install-src

  handlers:
    - name: "Start and enable rmon-{{ variant }}"
      systemd:
        name: "rmon-{{ variant }}"
        enabled: true
        state: started
        daemon_reload: true
      become: true
