---

- name: "Install scripts for the RMON-{{ variant }}"
  hosts: all
  gather_facts: true

  vars:
    variant: ~
    install_dir: ~
    release_tag: ~

  roles:
    - role: install-src
      tags: install-src

    - role: install
      tags: install

    - role: configure-system
      become: true
      tags:
        - install
        - install-src

    - role: uninstall
      become: true
      tags:
        - uninstall
        - uninstall-full

    - role: uninstall-full
      become: true
      tags: uninstall-full
