---

- name: Install scripts for the RMON-Server
  hosts: all
  gather_facts: true

  tasks:

    - name: Check if the rust toolchain is installed
      shell: command -v cargo
      changed_when: false
      tags: install-src

    - name: Install build requirements
      apt:
        pkg:
          - build-essential
          - protobuf-compiler
        update_cache: true
      become: true
      tags: install-src

    - name: Build binary from source
      command:
        cmd: cargo build --release
        chdir: /tmp/rmon-installer/rmon/server
        creates: /tmp/rmon-installer/rmon/server/target/release/rmon-server
      tags: install-src

    - name: Copy src build to installer directory
      copy:
        src: /tmp/rmon-installer/rmon/server/target/release/rmon-server
        dest: /tmp/rmon-installer/rmon-server
        mode: '0755'
        remote_src: true
      tags: install-src

    - name: Create rmon system user
      user:
        name: rmon
        comment: System user for the RMON suite
        system: true
      become: true
      tags:
        - install
        - install-src

    - name: Create target configuration directory /etc/rmon
      file:
        path: /etc/rmon
        owner: root
        group: rmon
        mode: '0750'
        state: directory
      become: true
      tags:
        - install
        - install-src

    - name: Create target installation directory /opt/rmon/bin
      file:
        path: /opt/rmon/bin
        owner: rmon
        group: rmon
        mode: '0755'
        state: directory
      become: true
      tags:
        - install
        - install-src

    - name: Copy binary to target installation directory
      copy:
        src: /tmp/rmon-installer/rmon-server
        dest: /opt/rmon/bin/rmon-server
        remote_src: true
        owner: rmon
        group: rmon
        mode: '0755'
      become: true
      tags:
        - install
        - install-src

    - name: Copy default config to target config directory
      copy:
        src: rmon-server.yaml
        dest: /etc/rmon/rmon-server.yaml
        owner: root
        group: root
        mode: '0644'
      become: true
      tags:
        - install
        - install-src

    - name: Copy systemd unit file
      copy:
        src: rmon-server.service
        dest: /usr/lib/systemd/system/rmon-server.service
        owner: root
        group: root
        mode: '0644'
      become: true
      notify: Start and enable rmon-server
      tags:
        - install
        - install-src

  handlers:
    - name: Start and enable rmon-server
      systemd:
        name: rmon-server
        enabled: true
        state: started
        daemon_reload: true
      become: true
